### ISSUE TITLE
Unstable test: AbstractDatasetTest.testTileSpeed 

### ISSUE THREAD

**Issue by jonahkichwacoders** [eclipse/january#154]
The testTileSpeed test is somtimes unstable. See for example https://hudson.eclipse.org/january/job/january-2.0/13/

I have marked build 13 as keep forever, please clear that flag once issue is resolved.

```
testTileSpeed(org.eclipse.january.dataset.AbstractDatasetTest)  Time elapsed: 6.389 sec  <<< FAILURE!
java.lang.AssertionError: Creation of tile took more than 50x as long as array creation of same size! (It took 6066ms)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.january.dataset.AbstractDatasetTest.runTile(AbstractDatasetTest.java:615)
	at org.eclipse.january.dataset.AbstractDatasetTest.testTileSpeed(AbstractDatasetTest.java:568)
```

**Comment by jonahkichwacoders** [comment]
In re-run of build test passed.
